LYING_IN_BED = "LYING_IN_BED"
SITTING_ON_BED = "SITTING_ON_BED"
SITTING_OUTSIDE_BED = "SITTING_OUTSIDE_BED"
STANDING = "STANDING"
WALKING = "WALKING"
OUT_OF_BED = "OUT_OF_BED"
LYING_OUTSIDE_BED = "LYING_OUTSIDE_BED"
UNKNOWN = "UNKNOWN"
NO_PERSON = "NO_PERSON"

STATE_ORDER = [LYING_IN_BED, SITTING_ON_BED, STANDING, WALKING,
               SITTING_OUTSIDE_BED, OUT_OF_BED, LYING_OUTSIDE_BED, UNKNOWN]
IN_STATES = {LYING_IN_BED, SITTING_ON_BED}
OUT_STATES = {SITTING_OUTSIDE_BED, STANDING, WALKING, OUT_OF_BED, LYING_OUTSIDE_BED}

ALLOWED = {
    LYING_IN_BED: {SITTING_ON_BED, LYING_OUTSIDE_BED},
    SITTING_ON_BED: {LYING_IN_BED, STANDING, LYING_OUTSIDE_BED},
    STANDING: {SITTING_ON_BED, WALKING, SITTING_OUTSIDE_BED, LYING_OUTSIDE_BED, OUT_OF_BED},
    WALKING: {STANDING, SITTING_ON_BED, SITTING_OUTSIDE_BED, LYING_OUTSIDE_BED, OUT_OF_BED},
    SITTING_OUTSIDE_BED: {STANDING, LYING_OUTSIDE_BED},
    LYING_OUTSIDE_BED: {SITTING_OUTSIDE_BED, STANDING, SITTING_ON_BED},
    OUT_OF_BED: {STANDING, WALKING},
}
